// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/sapcc/ontap-restapi/example/ontap/models"
	"github.com/spf13/cobra"
)

// Schema cli for ReturnedError

// register flags to command
func registerModelReturnedErrorFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerReturnedErrorPropCode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerReturnedErrorPropMessage(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerReturnedErrorPropReturnedErrorInlineArguments(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerReturnedErrorPropTarget(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerReturnedErrorPropCode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCodeDescription := `Error code`

	var flagCodeName string
	if cmdPrefix == "" {
		flagCodeName = "code"
	} else {
		flagCodeName = fmt.Sprintf("%v.code", cmdPrefix)
	}

	var flagCodeDefault string

	_ = cmd.PersistentFlags().String(flagCodeName, flagCodeDefault, flagCodeDescription)

	return nil
}

func registerReturnedErrorPropMessage(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagMessageDescription := `Error message`

	var flagMessageName string
	if cmdPrefix == "" {
		flagMessageName = "message"
	} else {
		flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
	}

	var flagMessageDefault string

	_ = cmd.PersistentFlags().String(flagMessageName, flagMessageDefault, flagMessageDescription)

	return nil
}

func registerReturnedErrorPropReturnedErrorInlineArguments(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: returned_error_inline_arguments []*ErrorArguments array type is not supported by go-swagger cli yet

	return nil
}

func registerReturnedErrorPropTarget(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagTargetDescription := `The target parameter that caused the error.`

	var flagTargetName string
	if cmdPrefix == "" {
		flagTargetName = "target"
	} else {
		flagTargetName = fmt.Sprintf("%v.target", cmdPrefix)
	}

	var flagTargetDefault string

	_ = cmd.PersistentFlags().String(flagTargetName, flagTargetDefault, flagTargetDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelReturnedErrorFlags(depth int, m *models.ReturnedError, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CodeAdded := retrieveReturnedErrorPropCodeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CodeAdded

	err, MessageAdded := retrieveReturnedErrorPropMessageFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MessageAdded

	err, ReturnedErrorInlineArgumentsAdded := retrieveReturnedErrorPropReturnedErrorInlineArgumentsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ReturnedErrorInlineArgumentsAdded

	err, TargetAdded := retrieveReturnedErrorPropTargetFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || TargetAdded

	return nil, retAdded
}

func retrieveReturnedErrorPropCodeFlags(depth int, m *models.ReturnedError, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCodeName := fmt.Sprintf("%v.code", cmdPrefix)
	if cmd.Flags().Changed(flagCodeName) {

		var flagCodeName string
		if cmdPrefix == "" {
			flagCodeName = "code"
		} else {
			flagCodeName = fmt.Sprintf("%v.code", cmdPrefix)
		}

		flagCodeValue, err := cmd.Flags().GetString(flagCodeName)
		if err != nil {
			return err, false
		}
		m.Code = &flagCodeValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveReturnedErrorPropMessageFlags(depth int, m *models.ReturnedError, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMessageName := fmt.Sprintf("%v.message", cmdPrefix)
	if cmd.Flags().Changed(flagMessageName) {

		var flagMessageName string
		if cmdPrefix == "" {
			flagMessageName = "message"
		} else {
			flagMessageName = fmt.Sprintf("%v.message", cmdPrefix)
		}

		flagMessageValue, err := cmd.Flags().GetString(flagMessageName)
		if err != nil {
			return err, false
		}
		m.Message = &flagMessageValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveReturnedErrorPropReturnedErrorInlineArgumentsFlags(depth int, m *models.ReturnedError, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagReturnedErrorInlineArgumentsName := fmt.Sprintf("%v.returned_error_inline_arguments", cmdPrefix)
	if cmd.Flags().Changed(flagReturnedErrorInlineArgumentsName) {
		// warning: returned_error_inline_arguments array type []*ErrorArguments is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveReturnedErrorPropTargetFlags(depth int, m *models.ReturnedError, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagTargetName := fmt.Sprintf("%v.target", cmdPrefix)
	if cmd.Flags().Changed(flagTargetName) {

		var flagTargetName string
		if cmdPrefix == "" {
			flagTargetName = "target"
		} else {
			flagTargetName = fmt.Sprintf("%v.target", cmdPrefix)
		}

		flagTargetValue, err := cmd.Flags().GetString(flagTargetName)
		if err != nil {
			return err, false
		}
		m.Target = &flagTargetValue

		retAdded = true
	}

	return nil, retAdded
}
